# Generated by Django 4.2.5 on 2023-09-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_unit_alter_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tent_name', models.CharField(max_length=255)),
                ('tent_uname', models.CharField(max_length=255)),
                ('tent_pword', models.CharField(max_length=255)),
                ('num_pip', models.IntegerField()),
            ],
        ),
    ]
