# Generated by Django 4.2.5 on 2023-09-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_tenants_groups_alter_tenants_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenants',
        ),
    ]
