# Generated by Django 4.2.5 on 2023-09-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
