# Generated by Django 4.2.7 on 2023-11-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_booked_image_alter_admin_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='pword',
            field=models.CharField(default='admin_password', max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='uname',
            field=models.CharField(default='admin_username', max_length=255),
        ),
    ]
