# Generated by Django 4.2.5 on 2023-09-26 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_delete_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tent_name', models.CharField(max_length=255)),
                ('tent_uname', models.CharField(max_length=255)),
                ('unit_type', models.CharField(max_length=255)),
                ('tent_pnum', models.CharField(max_length=255)),
                ('tent_emel', models.CharField(default='custom@example.com', max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('tent_pword', models.CharField(max_length=255)),
            ],
        ),
    ]
