# Generated by Django 4.2.5 on 2023-09-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_alter_tenants_options_alter_tenants_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='tent_pword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='tent_uname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
