# Generated by Django 4.2.5 on 2023-09-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_alter_tenants_tent_pword_alter_tenants_tent_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='tent_uname',
            field=models.CharField(default='default', max_length=255, unique=True),
        ),
    ]
