# Generated by Django 4.2.5 on 2023-09-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_alter_tenants_tent_uname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenants',
        ),
    ]
