# Generated by Django 4.2.1 on 2023-12-07 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_payment_unitid_alter_booked_ref_and_more'),
    ]

    # operations = [
    #    migrations.AlterField(
    #        model_name='payment',
    #        name='unitId',
    #        field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.units'),
     #   ),
    #] 
