# Generated by Django 4.2.5 on 2023-09-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_delete_tenants'),
        ('coreapp', '0010_tenants'),
    ]

    operations = [
    ]
