# Generated by Django 4.2.1 on 2023-12-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_alter_payment_unitid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='ref',
            field=models.IntegerField(default=1),
        ),
    ]
