# Generated by Django 4.2.1 on 2023-12-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_alter_booked_ref'),
    ]

    operations = [
       # migrations.RemoveField(
        #    model_name='payment',
        #    name='unitId',
       # ),
        migrations.AddField(
            model_name='payment',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.units'),
        ),
    ]
