# Generated by Django 4.2.1 on 2023-12-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_remove_payment_unitid_payment_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='total_sales',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
