# Generated by Django 4.2.1 on 2023-12-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_units_total_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='date',
        ),
        migrations.AddField(
            model_name='booked',
            name='chek_in',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='chek_out',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
