# Generated by Django 4.2.5 on 2023-09-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coreapp', '0013_tenantaccs_delete_tenants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenantaccs',
            new_name='Tenants',
        ),
    ]
