# Generated by Django 4.2.1 on 2023-12-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_remove_booked_date_booked_chek_in_booked_chek_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='chek_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booked',
            old_name='chek_out',
            new_name='check_out',
        ),
    ]
