# Generated by Django 4.2.5 on 2023-10-12 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_books_units_delete_unit_alter_tenants_tent_pnum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pnum', models.IntegerField()),
                ('date', models.DateField(max_length=255)),
                ('emel', models.CharField(default='custom@example.com', max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.units')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
