# Generated by Django 4.2.5 on 2023-10-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_booked_delete_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='bookt',
            field=models.CharField(default='duration', max_length=255),
        ),
    ]
