# Generated by Django 4.2.5 on 2023-10-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_booked_bookt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='unit',
            field=models.CharField(max_length=255),
        ),
    ]
