# Generated by Django 4.2.5 on 2023-10-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_alter_booked_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('ref', models.CharField(max_length=255)),
                ('mop', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.tenants')),
            ],
        ),
    ]
