# Generated by Django 4.2.5 on 2023-10-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0019_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.CharField(default='date', max_length=255),
        ),
    ]
