# Generated by Django 4.2.5 on 2023-10-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0021_alter_tenants_tent_emel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
