# Generated by Django 4.2.5 on 2023-10-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0025_alter_payment_name'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='tenants',
    #         name='tent_uname',
    #         field=models.CharField(max_length=255, unique=True),
    #     ),
    # ]
