# Generated by Django 4.2.5 on 2023-10-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0029_alter_tenants_tent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default='date', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.IntegerField(max_length=255),
        ),
    ]
