# Generated by Django 4.2.5 on 2023-10-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0032_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='num_unit',
        ),
        migrations.AddField(
            model_name='units',
            name='unit_blt',
            field=models.CharField(default='location', max_length=255),
        ),
        migrations.AddField(
            model_name='units',
            name='unt_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='unt_price',
            field=models.FloatField(),
        ),
    ]
