# Generated by Django 4.2.5 on 2023-10-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0033_remove_units_num_unit_units_unit_blt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issue', models.CharField(default='location', max_length=255)),
                ('want_sol', models.CharField(max_length=255)),
            ],
        ),
    ]
