# Generated by Django 4.2.5 on 2023-10-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0034_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='issue',
            field=models.CharField(max_length=255),
        ),
    ]
