# Generated by Django 4.2.5 on 2023-10-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0035_alter_issues_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='want_sol',
            new_name='solution',
        ),
    ]
