# Generated by Django 4.2.5 on 2023-10-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0036_rename_want_sol_issues_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='pnum',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='tent_pnum',
            field=models.CharField(max_length=20),
        ),
    ]
