# Generated by Django 4.2.5 on 2023-10-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0037_alter_booked_pnum_alter_tenants_tent_pnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
