# Generated by Django 4.2.5 on 2023-10-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0038_booked_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='assigned_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.units'),
        ),
    ]
