# Generated by Django 4.2.5 on 2023-10-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0039_tenants_assigned_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenants',
            old_name='assigned_unit',
            new_name='assigned_unit_id',
        ),
    ]
