# Generated by Django 4.2.5 on 2023-11-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0042_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('decline', 'Decline')], default='Pending', max_length=20),
        ),
    ]
